### ISSUE TITLE
Incorrect instructions in Read-me

### ISSUE THREAD

**Issue by Clepsyd** [EvelinaClayton/acebook-derailed-team#20]
- No instruction for migrations, should instruct to run `db:migrate` and `db:schema:load` after `db:create`

- `rails generate clearance:install` unnecessary as the files generated by this command have already been committed

**Comment by nervecell23** [comment]
For the first one, I think the last ‘db:migrate’ should do the work, no need to run db:migrate twice, what do you think?

For the second one, when Jamal pull the master previously, we had error which was solved by running that line, but your suggestion sounds right, we should investigate further.
